backend:
  name: github
  branch: main
  repo: nguyenquyynh/doc.web

# These lines should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads

collections:
- name: Doc (VI)
  label: "Doc (VI)"
  label_singular: "Doc (VI)"
  folder: docs
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  delete: true
  nested: { depth: 100 }
  slug: "{{slug}}"
  summary: "/{{dirname}}/{{filename}}.{{extension}}"
  fields:
    - { name: title, label: Title, widget: string }
    - { name: label, label: Label, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string, required: false }
  meta: { path: { widget: string, label: 'Path', index_file: 'index' } }